FROM python:3.8.0-alpine

RUN mkdir -p /app/djangoapp
WORKDIR /app/djangoapp

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install psycopg2 dependencies
RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev


# install dependencies
RUN pip install --upgrade pip
COPY requirement.txt /app/djangoapp/
RUN pip install -r requirement.txt

# copy entrypoint.sh
COPY ./entrypoint.sh /app/djangoapp/hello_django/entrypoint.sh

# copy app
COPY . /app/djangoapp/

# run entrypoint.sh
ENTRYPOINT ["/app/djangoapp/hello_django/entrypoint.sh"]

# expose the port 8000
EXPOSE 8000

CMD ["gunicorn", "-c", "/app/djangoapp/hello_django/gunicorn/conf.py", "--bind", ":8000", "--chdir", "hello_django", "hello_django.wsgi:application"]
